---
title: "HW_for D.S.1"
author: "Nadezhda Tsurikova"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
data1 <- read.csv("insurance_cost.csv",
                           stringsAsFactors = FALSE)
```

```{r}
hist(data1$age)
```

```{r}
hist(data1$bmi)
```

```{r}
hist(data1$charges)
```

*график плотности по колонке charges*

```{r}
charges_mean <- round(mean(data1$charges))
charges_median <- round(median(data1$charges))

 ggplot(data1, 
       aes(charges)) +
  geom_density(fill="lightblue") +
  geom_vline(aes(xintercept = charges_median)) +
  annotate("text", 
           x= charges_median, 
           y=0.00004,
           label=paste0("Median=", charges_median))+
  geom_vline(aes(xintercept = charges_mean), 
             color="blue", linetype="dashed", size=1) +
  annotate("text", 
           x= charges_mean, 
           y=0.00001,
           label=paste0("Mean=", charges_mean), color="blue")+
  labs(title="график плотности по колонке charges",x="charges", y = "Density")
  theme_minimal()
  
  
```

*box_plot отношение переменных charges и sex*

```{r}
boxplot1 <- ggplot(data1, aes(x=sex, y=charges, fill=sex)) +
    geom_boxplot() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("boxplot SEX") +
    xlab("sex") +
  ylab("charges")

print(boxplot1)
```

*box_plot отношение переменных charges и smoker*

```{r}
boxplot2 <- ggplot(data1, aes(x=smoker, y=charges, fill=smoker)) +
    geom_boxplot() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("boxplot smoker") +
    xlab("smoker") +
  ylab("charges")

print(boxplot2)
```

*box_plot отношение переменных charges и region*

```{r}
boxplot3 <- ggplot(data1, aes(x=region, y=charges, fill=region)) +
    geom_boxplot() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("boxplot region") +
    xlab("region") +
  ylab("charges")

print(boxplot3)
```
*отношение charges и переменных: sex, smoker, region*

```{r}
library(ggpubr)

dd <- ggplot(data1, 
       aes(charges)) +
  geom_density(fill="lightblue")

combo <- ggarrange(dd, boxplot1, boxplot2, boxplot3, ncol = 1, nrow = 3)
print(combo)

```

*фасет графика по region*

```{r}
library(dplyr)

data1 %>% 
  filter(charges != 0) %>% 
  ggplot(aes(x=age, y= charges, color = region, fill = region, group = region)) + 
  geom_point() +
  facet_grid(. ~ region) +
  geom_smooth(method=lm, 
              fullrange = T, 
              alpha = 0.2,
              se=TRUE 
              )+
  theme_minimal() +
  ggtitle('Распределение расходов относительно возрастных групп в зависимости от региона') + 
  labs(y = 'Расходы', x ='Регион с учетом возрастных групп') +
  theme(
    title = element_text(size = 14), 
    axis.title.y = element_text(size=12) 
    )
```

*График сравнения расходов по регионам в зависимости от статуса курения*

```{r}
data1 %>% 
  filter(charges != 0) %>% 
  ggplot(aes(x=age, y= charges, color = smoker, fill = smoker, group = smoker)) + 
  geom_point() +
  facet_grid(. ~ region) +
  geom_smooth(method=lm, 
              fullrange = T, 
              alpha = 0.2,
              se=TRUE 
              )+
  theme_minimal() +
  ggtitle('сравнение расходов по регионам в зависимости от статуса курения') + 
  labs(y = 'Расходы', x ='Регион с учетом возрастных групп') +
  theme(
    title = element_text(size = 14), 
    axis.title.y = element_text(size=12) 
    )
```

*Отношение ИМТ и расходов*

```{r}
data1 %>% 
  filter(bmi != 0) %>% 
  ggplot(aes(x=bmi, y=charges, color=bmi)) + 
    geom_point(size=3)
```

```{r}
data1 %>% 
  filter(charges != 0) %>% 
  ggplot(aes(x=bmi, y= charges, color = region, fill = region, group = region)) + 
  geom_point() +
  facet_grid(. ~ region) +
  geom_smooth(method=lm, 
              fullrange = T, 
              alpha = 0.2,
              se=TRUE 
              )+
  theme_minimal() +
  ggtitle('Распределение расходов относительно ИМТ в зависимости от региона') + 
  labs(y = 'Расходы', x ='ИМТ(распределение по регионам)') +
  theme(
    title = element_text(size = 14), 
    axis.title.y = element_text(size=12) 
    )
```


```{r}
data1 %>% 
  filter(charges != 0) %>% 
  ggplot(aes(x=bmi, y= charges, color = smoker, fill = smoker, group = smoker)) + 
  geom_point() +
  facet_grid(. ~ region) +
  geom_smooth(method=lm, 
              fullrange = T, 
              alpha = 0.2,
              se=TRUE 
              )+
  theme_minimal() +
  ggtitle('сравнение расходов по регионам в зависимости от статуса курения') + 
  labs(y = 'Расходы', x ='ИМТ(распределение по регионам)') +
  theme(
    title = element_text(size = 14), 
    axis.title.y = element_text(size=12) 
    )
```

```{r}
data1 <- data1 %>% 
  mutate(
      age_group = case_when(
      age < 35 ~ "21-34",
      age >= 35 & age < 50 ~ "35-49",
      age >= 50 ~ "50+"
    ))
```

```{r}
log_scale <- data1 %>% 
  filter(charges != 0) %>% 
  ggplot(aes(x=bmi, y= charges, color = age_group, fill = age_group, group = age_group)) + 
  geom_point() +
  facet_grid(. ~ age_group) +
  geom_smooth(method=lm, 
              fullrange = T, 
              alpha = 0.2,
              se=TRUE 
              )+
  theme_minimal() +
  ggtitle('сравнение расходов по в зависимости от возраста') + 
  labs(y = 'Расходы', x ='ИМТ') +
  theme(
    title = element_text(size = 14), 
    axis.title.y = element_text(size=12) 
    )
print(log_scale)
```

```{r}
log_scale + scale_x_continuous(trans = 'log2')
```

